spring.application.name=MESSAGING-SERVICE
server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.data.mongodb.uri=mongodb+srv://supun:root@cluster0.vzxikyx.mongodb.net/decp_messages?retryWrites=true&w=majority
