server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**
        - id: opportunity-service
          uri: lb://OPPORTUNITY-SERVICE
          predicates:
            - Path=/jobs/**,/events/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka