spring.application.name=USER-SERVICE

server.port=8081
spring.data.mongodb.uri=mongodb+srv://supun:root@cluster0.vzxikyx.mongodb.net/decp_users?retryWrites=true&w=majority
eureka.client.service-url.defaultZone=http://localhost:8761/eureka