spring.application.name=OPPORTUNITY-SERVICE
server.port=8083
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
spring.data.mongodb.uri=${OPPORTUNITY_DB_URI}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
